# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtGui import QIcon

class Web_Form(object):
    def setupUi(self, Form):
        self.formLayout = QtWidgets.QVBoxLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.browser = QWebEngineView(Form)
        self.formLayout.addWidget(self.browser)
        self.retranslateUi(Form)
        self.setWindowState(QtCore.Qt.WindowMaximized)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Просмотр документа"))

class progressForm(object):
    def setupUi(self, Form):
        Form.resize(400, 50)
        self.formLayout = QtWidgets.QVBoxLayout(self)
        self.formLayout.setObjectName("formLayout")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.addWidget(self.progressBar)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", u"Идет отправка исследования, подождите"))     
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 550)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.verticalLayout.addLayout(self.formLayout)
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout.addWidget(self.searchButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendButton = QtWidgets.QPushButton(Form)
        self.sendButton.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.get3DModelButton = QtWidgets.QPushButton(Form)
        self.get3DModelButton.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.get3DModelButton.setFont(font)
        self.get3DModelButton.setObjectName("get3DModelButton")
        self.horizontalLayout.addWidget(self.get3DModelButton)
        self.getReportButton = QtWidgets.QPushButton(Form)
        self.getReportButton.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.getReportButton.setFont(font)
        self.getReportButton.setObjectName("getReportButton")
        self.horizontalLayout.addWidget(self.getReportButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        #self.progressBar = QtWidgets.QProgressBar(Form)
        #self.progressBar.setProperty("value", 0)
        #self.progressBar.setObjectName("progressBar")
        #self.verticalLayout_2.addWidget(self.progressBar)
        self.setWindowState(QtCore.Qt.WindowMaximized)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Thorax PACS"))
        self.label_5.setText(_translate("Form", "Дата исследования"))
        self.searchButton.setText(_translate("Form", "Поиск"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "UID исследования"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ФИО пациента"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Номер истории"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Дата исследования"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Обработано"))
        self.sendButton.setText(_translate("Form", "Отправить на обработку"))
        self.get3DModelButton.setText(_translate("Form", "Просмотр 3D модели"))
        self.getReportButton.setText(_translate("Form", "Просмотр отчета"))
        
